language: go
go:
- 1.5
env:
- TEST_MONGO="true"
services:
- mongodb
install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/golang/lint/golint
- go get github.com/tools/godep
before_script:
- ./monitor/insert_test_data.bash
script:
- go vet ./...
- golint ./...
- cd monitor
- godep go build -o gmonitor.$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER github.com/typingincolor/go-galen/monitor/gmonitor
- ./test.bash
addons:
  artifacts:
    s3_region: eu-west-1
    bucket: typingincolor-gogalen-artifacts
    key:
      secure: ceJppxEawPtRt9hE2l+sDEcuPKzUB3P+8SXLkZw7jktXr+Y0p5sqOwOQ6tmNk9UyqhF3swICtzOUki7yHYg22Qp9EptNys+5zEpse2KLuperTyoX03Npszv/d9HH/GhtymWmIY2X++udUB+dEd3Wrwt9J6FQrVWmnSx0tIzm6wtx8SDvkqlnU83jAF/PvClADFYkeCyEN+XC6B7q6bU7IZ/CHKF4F3E6t4T/HB/qKg5jFq4oGQfL6teVxUK5n1+i85lXtEWT0gZHYzrDazEF20llvMThbFEXDRLUbmaMLU4hzbtCnpnqSuC5eGcuR3sBsO26FsFBnG7TbH+vDwsCjowE4gMvDEzMJMy+aT6k8VL30lnuuq8iiVGDVrhWbZbkoBI883/I0zHTIOBiSc/Zo4dp52l2VwLOalA8ghFLqNw2jp4TG9Ffm3QLpxbXp615mbPEu8WUvH9Oy/oBvz8Ja7GXsE8yElN6u8LBHqri9oBvegKwPvidZX9nT6eLp+a041669gAbQTEzJK470BAsKfwjZizIzUPe9dUCqMpEXtpts8zncoNb4NRtLkRrMPeLH2Y3eXpTlND19W77lQ5GRd6HXaINfMyNLdG8HOPfT0wnAdiM5EfiVhcWQnQVnoi6iI0/kdYjRk6DlxPZbOAuCsKGJxda7E9VmkBqZO8UJxk=
    secret:
      secure: b3xloQTD46nZg1ZSf3r3yr7gZb+KO8VO0rowk+6GKnBNEt2pU/eyQjBQE7+cWSuADBKs5vy0KOMqQTqb5rywEJhuZuV/+vNYGtWnuiNH9M6AFVe8WddPSyNEAQW5Hat7qFIC8ue3y4s93YQRcR7AjRdX4NynFtX2Rqlxa2mc+vXXQPkDO1ygYrm8pG9PFg1C/i0Fnxsal3AwrI/ojkfb3MMEqydryxwMrnmcJ/5dnv1612xZDqHLj2t6PeTOxe5YjhgLf2vdc4u3MhJDXD81Vlzsor2ucR8uxh3eHmESH/xjbR2Poxcmuy43HPU61b04i2qQIZsGUqzYBBLcb0fzrQuLQ9xRfmJDHqQ4Eo2Uly2dB6Tep+xQ2TBSsI6QzXYMfPplp4uUSLAIWxphUUu+6CV3w0BkiVGcGoaIgH9ug06mBr7oZPWDL4p2/0V5wSzPdJfWOtu8NAdiPVrr48k7tEpyiVBFTF/J4kh/dul3aTC9n5FeGCkS7Dvx/YpiMFTCN5tWYcs03dUhP3CDF2yjpXDUUgNg8/i9Q42EN2HX4yufJ2jb5loY9+QIXPU8C6gq65t/hHp5fOTuxOGHBccVogG2NHSkXwTxbTnSzGhhKkUYClw+VcSiYXW9yINrE8i2zndZmYxSzBjk8oOX6R8ywWTxsNce+1jEPi6FxoAbjMY=
