language: go
go:
  - 1.5
install:
  - go get github.com/Sirupsen/logrus
  - go get gopkg.in/mgo.v2
  - go get github.com/stretchr/testify/assert
script:
  - go test ./...
  - go build github.com/typingincolor/go-galen/monitor/gmonitor
